### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by thom966** [TUI-NICR/EMSAFormer#1]
Dear author,

Hello, I am writing to express my gratitude for your excellent research showcased in your paper.
By the way, an error was encountered while attempting to train the model according to the command specified in the readme.

The error message:

```
File "/mnt/sdc/EMSAFormer/lib/nicr-multitask-scene-analysis/nicr_mt_scene_analysis/model/decoder/panoptic.py", line 52, in forward
    res_semantic = self.semantic_decoder.forward(
  File "/mnt/sdc/EMSAFormer/lib/nicr-multitask-scene-analysis/nicr_mt_scene_analysis/model/decoder/base.py", line 45, in forward
    output = self._forward_training(x, skips)
  File "/mnt/sdc/EMSAFormer/lib/nicr-multitask-scene-analysis/nicr_mt_scene_analysis/model/decoder/mlp_base.py", line 149, in _forward_training
    features.append(branch(x_fused))
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (NoneType, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of: (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
```

I figured out that `x_fused = fusion(x_enc=skip, x_dec=None) ` at line 147 in `mlp_base.py` returns `None` type, so that the feature cannot be processed furthur.

Could you please tell me how to handle this issue?
Thank you for your time.

**Comment by Tripton** [comment]
Thanks for reaching out.
Unfortunately, we are unable to reproduce the error you mentioned.
Could you please execute the command again and provide us with the full logs? This will help us in investigating the issue.

**Comment by thom966** [comment]
Dear author,

Here is the full error log:

```
[Warning] Set `encoder-fusion` to 'none' as there is only one input modality.
[Warning] Forced `semantic-no-multiscale-supervision` as `semantic-decoder` is 'segformer
[Warning] Dataset 'nyuv2' does not have a 'valid' split, using 'test' split instead.
Running with args:                                                                       
 {                                                                              
    "action": null,
    "activation": "relu",                                                       
    "aug_scale_max": 1.4,                                                                
    "aug_scale_min": 1.0,                                                                
    "batch_size": 8,
    "cache_dataset": false,                                                     
    "checkpointing_best_only": true,
    "checkpointing_metrics": [                                                  
        "valid_semantic_miou",                                                           
        "bacc",                                                                          
        "panoptic_deeplab_semantic_miou",
        "panoptic_all_with_gt_deeplab_pq"                                       
    ],                                                                                   
    "checkpointing_skip": 0.8,                                                  
    "compile_model": false,                     
    "context_module": "ppm",                                                    
    "dataset": "nyuv2",
    "dataset_path": "./datasets/nyuv2",                                         
    "debug": false,
    "decoder_normalization": "batchnorm",                                       
    "depth_encoder_backbone": "resnet34",
    "depth_encoder_backbone_block": null,                                       
    "depth_encoder_backbone_pretrained_weights_filepath": null,                              "depth_encoder_backbone_resnet_block": "nonbottleneck1d",
    "dropout_p": 0.1,
    "enable_panoptic": true,                                                                 "encoder_decoder_fusion": null,                                                      
    "encoder_decoder_skip_downsamplings": [                                                      4,                                                                                       8,                                                                                       16                                                                                   ],                                                                              
    "encoder_fusion": "none",                                                            
    "encoder_normalization": "layernorm",                                                
    "he_init": [                                              
        "encoder-fusion"                                                     
    ],                                         
"hostname": "LearningMachine4",                                             
    "hypersim_subsample": 1,                                                        
    "input_height": 480,                                                                 
    "input_modalities": [                                                                
        "rgbd"                                                                  
    ],             
    "input_width": 640,                                                         
    "instance_center_encoding": "sigmoid",                                               
    "instance_center_heatmap_apply_foreground_mask": false,                              
    "instance_center_heatmap_nms_kernel_size": 17,
    "instance_center_heatmap_threshold": 0.1,                                   
    "instance_center_heatmap_top_k": 64,
    "instance_center_loss": "mse",                                              
    "instance_center_sigma": 8,                                                          
    "instance_decoder": "emsanet",                                                       
    "instance_decoder_block": "nonbottleneck1d",
    "instance_decoder_block_dropout_p": 0.2,                                    
    "instance_decoder_downsamplings": [                                                  
        16,                                                                     
        8,                                      
        4                                                                       
    ],                 
    "instance_decoder_dropout_p": 0.1,                                          
    "instance_decoder_n_blocks": 3,
    "instance_decoder_n_channels": [                                            
        512,                             
        256,                                                                    
        128                                                                                  ],                                                       
    "instance_decoder_upsampling": "learned-3x3-zeropad",
    "instance_encoder_decoder_fusion": "swin-ln-add",                                        "instance_no_multiscale_supervision": false,                                         
    "instance_offset_distance_threshold": null,                                              "instance_offset_encoding": "tanh",                                                      "instance_weighting": [                                                                      2,                                                                                       1                                                                           
    ],                                                                                   
    "is_resumed_training": false,                                                        
    "learning_rate": 0.03,                                    
    "learning_rate_scheduler": "onecycle",                                   
    "momentum": 0.9,
"n_epochs": 500,                                                            
    "n_workers": 8,                                                                 
    "no_pretrained_backbone": false,                                                     
    "no_zero_init_decoder_residuals": false,                                             
    "normal_decoder": "emsanet",                                                
    "normal_decoder_block": "nonbottleneck1d",
    "normal_decoder_block_dropout_p": 0.2,                                      
    "normal_decoder_downsamplings": [                                                    
        16,                                                                              
        8,                                        
        4                                                                       
    ],                                  
    "normal_decoder_dropout_p": 0.1,                                            
    "normal_decoder_n_blocks": 3,                                                        
    "normal_decoder_n_channels": [                                                       
        512,                                    
        256,                                                                    
        128                                                                              
    ],                                                                          
    "normal_decoder_upsampling": "learned-3x3-zeropad",
    "normal_encoder_decoder_fusion": "add-rgb",                                 
    "normal_loss": "l1",
    "normal_no_multiscale_supervision": false,                                  
    "normalization": null,         
    "notes": "",                                                                
    "optimizer": "sgd",                  
    "orientation_kappa": 1.0,                                                   
    "overfit_n_batches": -1,                                                                 "raw_depth": false,                                      
    "results_basepath": "./results/nyu-swin-mlp",        
    "resume_ckpt_filepath": null,                                                            "resume_ckpt_interval": 20,                                                          
    "resume_path": null,                                                                     "rgb_encoder_backbone": "resnet34",                                                      "rgb_encoder_backbone_block": null,                                                      "rgb_encoder_backbone_pretrained_weights_filepath": null,                                "rgb_encoder_backbone_resnet_block": "nonbottleneck1d",                         
    "rgbd_encoder_backbone": "swin-multi-t-v2-128",                                      
    "rgbd_encoder_backbone_pretrained_weights_filepath": "./trained_models/imagenet/swin_
multi_t_v2_128.pth",                                          
    "rgbd_encoder_backbone_resnet_block": "nonbottleneck1d",                 
    "scannet_semantic_n_classes": 40,
"scannet_subsample": 50,                                                    
    "scene_loss_label_smoothing": 0.1,                                              
    "semantic_class_weighting": "median-frequency",                                      
    "semantic_class_weighting_logarithmic_c": 1.02,                                      
    "semantic_decoder": "segformermlp",                                         
    "semantic_decoder_block": "nonbottleneck1d",
    "semantic_decoder_block_dropout_p": 0.2,                                    
    "semantic_decoder_downsamplings": [                                                  
        16,                                                                              
        8,                                        
        4                                                                       
    ],                                  
    "semantic_decoder_dropout_p": 0.1,                                          
    "semantic_decoder_n_blocks": 3,                                                      
    "semantic_decoder_n_channels": [                                                     
        256,                                    
        128,                                                                    
        64,                                                                              
        64                                                                      
    ],                                                 
    "semantic_decoder_upsampling": "bilinear",                                  
    "semantic_encoder_decoder_fusion": "swin-ln-select",
    "semantic_loss_label_smoothing": 0.0,                                       
    "semantic_no_multiscale_supervision": true,
    "skip_sanity_check": false,                                                 
    "subset_deterministic": false,       
    "subset_train": 1.0,                                                        
    "sunrgbd_depth_do_not_force_mm": false,                                                  "tasks": [                                               
        "semantic",                                      
        "scene",                                                                                 "instance",                                                                      
        "orientation"                                                                        ],                                                                                       "tasks_weighting": [                                                                         1.0,                                                                                     0.25,                                                                       
        2.0,                                                                             
        0.5                                                                              
    ],                                                        
    "upsampling_context_module": "bilinear",                                 
    "upsampling_decoder": null,
"upsampling_prediction": "learned-3x3-zeropad",                             
    "use_original_scene_labels": false,                                             
    "validation_batch_size": 8,                                                          
    "validation_force_interval": 20,                                                     
    "validation_full_resolution": false,                                        
    "validation_input_height": 480,             
    "validation_input_width": 640,                                              
    "validation_only": false,                                                            
    "validation_scannet_benchmark_mode": false,                                          
    "validation_scannet_subsample": 100,          
    "validation_skip": 10.0,                                                    
    "validation_split": "test",         
    "visualization_output_path": null,                                          
    "visualize_validation": false,                                                       
    "wandb_mode": "disabled",                                                            
    "wandb_name": null,                         
    "wandb_project": "EMSAFormer",                                              
    "weight_decay": 0.0001,                                                              
    "weights_filepath": null                                                    
}                                                      
Writing results to '/mnt/sdc/EMSAFormer/results/nyu-swin-mlp/nyuv2/run_2023_06_14-1
2_10_49-643185'.                                        
Get model and dataset                                                           
Loading pretrained weights from: './trained_models/imagenet/swin_multi_t_v2_128.pth'
Computing class weights for 'semantic' ...                                      
100%|███████████████████████████████████████| 795/795 [00:00<00:00, 1444.90it/s]
Perform sanity check                                                            
Traceback (most recent call last):                                                         File "main.py", line 709, in <module>                      
    main()                                               
  File "main.py", line 460, in main                                                          assert isinstance(run.training_step(batch, 0), torch.Tensor)                         
  File "main.py", line 112, in training_step                                                 predictions_post = self.model(batch, do_postprocessing=True)                           File "/mnt/sdc/yhson/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl                                                    return forward_call(*args, **kwargs)                                            
  File "/mnt/sdc/EMSAFormer/emsaformer/model.py", line 223, in forward             
    decoder(                                                                             
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/mod
ules/module.py", line 1501, in _call_impl                                    
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/EMSAFormer/lib/nicr-multitask-scene-analysis/nicr[0/1859]e_analysis/model/decoder/panoptic.py", line 52, in forward
    res_semantic = self.semantic_decoder.forward(
  File "/mnt/sdc/EMSAFormer/lib/nicr-multitask-scene-analysis/nicr_mt_scene_analysis/model/decoder/base.py", line 45, in forward
    output = self._forward_training(x, skips)
  File "/mnt/sdc/EMSAFormer/lib/nicr-multitask-scene-analysis/nicr_mt_scene_analysis/model/decoder/mlp_base.py", line 151, in _forward_training
    features.append(branch(x_fused))
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/sdc/anaconda3/envs/emsaformer/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (NoneType, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType,
Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType,
Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)

```

**Comment by danielS91** [comment]
Unfortunately, we are still not able to reproduce the issue.
`x_fused` can only be `None` if encoder-decoder fusion is disabled (see [HERE](https://github.com/TUI-NICR/nicr-multitask-scene-analysis/blob/6a618cf89fff716b8059c0d81a7ac207ef16d4a3/nicr_mt_scene_analysis/model/encoder_decoder_fusion.py#L72)).
However, according to the args `semantic_encoder_decoder_fusion` is `swin-ln-select`. So the fusion seems to be fine.

Did you modify other parts of the code that may be the reason?
Otherwise, it would be helpful to start debugging in the fusion itself, i.e., [HERE](https://github.com/TUI-NICR/nicr-multitask-scene-analysis/blob/6a618cf89fff716b8059c0d81a7ac207ef16d4a3/nicr_mt_scene_analysis/model/encoder_decoder_fusion.py#L148):
- is `self._fuse_features_from` determined correctly? 
- what is `self._fuse_operation`?
- what is `x_enc`?
- what is `x_c`?

**Comment by thom966** [comment]
Dear author,

I have notices that an unintended modification took place during the installation of the modified library of "nicr-multitask-scene-analysis" from the EMSANet, wherein the value of the attribute "self._fuse_operation" was mistakenly set to None.

I sincerely apologize for this oversight on my part, and I would like to express my deep gratitude for your valuable responses and assistance.
